### ISSUE TITLE
Backers

### ISSUE THREAD

**Issue by Ecogenesis-biomaterials** [Bambu-Research-Group/RFID-Tag-Guide#38]
Hello, my name is Fred Pinczuk CTO of Ecogenesis Biopolymers, we are about to launch the 1st 100% biomade TPU that is naturally biodegradable (ASTM6691). And believe open source RIFD tag for material rolls is a must. Please add us to the list of backers. 
We are currently working with Polar as a converter and re-seller of our products.

**Comment by thekakester** [comment]
Added you to the backers list.  Is there a good website to use?  I used https://ecogenesisbiopolymers.com, let me know if I should change that.

**Comment by Ecogenesis-biomaterials** [comment]
Thank you, we hope to have the website up shortly. Yes, that works perfect.
