### ISSUE TITLE
Hardware/Firmware info

### ISSUE THREAD

**Issue by csBlueChip** [Bambu-Research-Group/RFID-Tag-Guide#39]
Has anyone dumped the firmware yet? PCB photos? Firmware upgrade files?

**Comment by warbarz** [comment]
See our discord. Yes to all.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: BlueChip ***@***.***> Date: 9/20/24  11:34 AM  (GMT-06:00) To: Bambu-Research-Group/RFID-Tag-Guide ***@***.***> Cc: Subscribed ***@***.***> Subject: [Bambu-Research-Group/RFID-Tag-Guide] Hardware/Firmware info (Issue #39) 
Has anyone dumped the firmware yet? PCB photos? Firmware upgrade files?

**Comment by csBlueChip** [comment]
Awesome. Forgive my weak Google-fu, where can I find an invite?

**Comment by csBlueChip** [comment]
Found it: https://github.com/Bambu-Research-Group/RFID-Tag-Guide/issues/4#issuecomment-1837178129
See you there...
