### ISSUE TITLE
Flipper Zero RFID files

### ISSUE THREAD

**Issue by oldbug62** [Bambu-Research-Group/RFID-Tag-Guide#8]
I used the Flipper Zero to read my Bambu filaments. Perhaps helpful? 
just delete .txt

[PLA_Basic_Bambu Green #16C344.nfc .txt](https://github.com/Bambu-Research-Group/RFID-Tag-Guide/files/13260370/PLA_Basic_Bambu.Green.16C344.nfc.txt)
[PLA_Matte_Ice Blue #A3D8E1.nfc .txt](https://github.com/Bambu-Research-Group/RFID-Tag-Guide/files/13260371/PLA_Matte_Ice.Blue.A3D8E1.nfc.txt)

**Comment by pelrun** [comment]
Unfortunately not so much right now - if you look in the files you'll see that all the FZ got was the UID of the tag; the actual card contents are all ?? as you don't have the keys.
